# Generated by Django 4.1.5 on 2026-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0032_alter_microregistry_include_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='contract',
            field=models.ForeignKey(
                on_delete=models.RESTRICT,
                related_name='invoices',
                to='microinvoicer.servicecontract',
            ),
        ),
    ]
